version: '3' 

services:
    proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: proxy
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
        ports:
            - 80:80
            - 443:443
        volumes:
            - proxy_conf:/etc/nginx/conf.d:rw
            - proxy_vhost:/etc/nginx/vhost.d:rw
            - proxy_html:/usr/share/nginx/html:rw
            - ${PWD}/data/proxy/certs:/etc/nginx/certs:ro
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ${PWD}/proxy/upload_limits.conf:/etc/nginx/conf.d/upload_limits.conf:ro
        restart: unless-stopped
  
    database:
        image: mariadb
        container_name: database
        volumes:
            - db:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: unless-stopped
  
    nextcloud:
        image: nextcloud:latest
        container_name: nextcloud
        depends_on:
            - proxy
            - letsencrypt
            - database
            - redis
            - antivirus
        volumes:
            - ${PWD}/data/nextcloud:/var/www/html
            - /etc/localtime:/etc/localtime:ro
            - ${PWD}/nextcloud/setup.sh:/usr/local/bin/setup
        environment:
            - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
            - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=database
            - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
            - REDIS_HOST=redis
            - VIRTUAL_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
            - DEFAULT_APPS=${DEFAULT_APPS}
            - DEFAULT_ADMIN_APPS=${DEFAULT_ADMIN_APPS}
            - DOCUMENT_EDITOR_HOST=${DOCUMENT_EDITOR_SUBDOMAIN}.${DOMAIN}
        restart: unless-stopped
        
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        depends_on:
            - proxy
        volumes:
            - ${PWD}/data/proxy/certs:/etc/nginx/certs:rw
            - proxy_vhost:/etc/nginx/vhost.d:rw
            - proxy_html:/usr/share/nginx/html:rw
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        
    cron:
        image: nextcloud:latest
        container_name: cron
        volumes:
            - ${PWD}/data/nextcloud:/var/www/html
            - /etc/localtime:/etc/localtime:ro
        entrypoint: /cron.sh
        depends_on:
            - database
            - redis
        restart: unless-stopped
        
    antivirus:
        image: mkodockx/docker-clamav:latest
        container_name: antivirus
        restart: unless-stopped
        
    database-backup:
        image: fradelg/mysql-cron-backup
        container_name: database-backup
        depends_on:
            - database
        volumes:
            - ${PWD}/data/db_backup:/backup
            - /etc/localtime:/etc/localtime:ro
        environment:
            - MYSQL_HOST=database
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASS=${MYSQL_PASSWORD}
            - MYSQLDUMP_OPTS=--single-transaction
            - MAX_BACKUPS=${MAX_BACKUPS}
            - CRON_TIME=${CRON}
        restart: unless-stopped
        
    # This is for throwing a message if no document editor is selected
    document_editor:
        environment:
            - VIRTUAL_HOST=${DOCUMENT_EDITOR_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_HOST=${DOCUMENT_EDITOR_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        
volumes:
    db:  
    proxy_conf:
    proxy_vhost:
    proxy_html:
  
networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}
