version: '3'

services:
  ldap:
    image: osixia/openldap
    container_name: ldap
    command: --copy-service
    volumes:
      - ./data/ldap/config:/etc/ldap/slapd.d
      - ./data/ldap/database:/var/lib/ldap
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    depends_on:
      - ldap
    ports:
      - 6443:443
    environment:
      - VIRTUAL_HOST=${LDAP_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_HOST=${LDAP_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    restart: unless-stopped
