version: '3' 

services:
    mail:
       image: elsdoerfer/exim-sender
       container_name: mail
       networks:
            network:
                ipv4_address: 172.16.0.7
       environment:
            - ALLOWED_HOSTS=nextcloud
            - PRIMARY_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
       restart: unless-stopped
