version: '3' 

services:
    document_editor:
        image: onlyoffice/documentserver:latest
        container_name: onlyoffice
        stdin_open: true
        tty: true
        networks:
            - network
        depends_on:
            - proxy
            - letsencrypt
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        restart: unless-stopped 
        
    nextcloud:
        environment: 
            - DOCUMENT_EDITOR=onlyoffice
