    
version: '3' 

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - 8080:80
    depends_on:
        - database
    environment:
        - PMA_HOST=database
    restart: unless-stopped
