version: '3' 

services:
    proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: proxy
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
        networks:
            - network
        ports:
            - 80:80
            - 443:443
        volumes:
            - proxy-conf:/etc/nginx/conf.d:rw
            - proxy-vhost:/etc/nginx/vhost.d:rw
            - proxy-html:/usr/share/nginx/html:rw
            - proxy-certs:/etc/nginx/certs:ro
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - nextcloud:/var/www/html
        restart: unless-stopped
  
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        depends_on:
            - proxy
        networks:
            - network
        volumes:
            - proxy-certs:/etc/nginx/certs:rw
            - proxy-vhost:/etc/nginx/vhost.d:rw
            - proxy-html:/usr/share/nginx/html:rw
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
    
    database:
        image: mariadb
        container_name: database
        networks:
            - network
        volumes:
            - db:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: unless-stopped
  
    nextcloud:
        image: nextcloud:fpm
        container_name: nextcloud
        networks:
            - network
        depends_on:
            - letsencrypt
            - proxy
            - database
            - redis
        volumes:
            - nextcloud:/var/www/html
            - /etc/localtime:/etc/localtime:ro
        environment:
            - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
            - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=database
            - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
            - REDIS_HOST=redis
            - VIRTUAL_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        restart: unless-stopped
        
    redis:
        image: redis:alpine
        container_name: redis
        networks:
            - network
        restart: unless-stopped
        
volumes:
    nextcloud:
    db: 
    proxy-conf:
    proxy-vhost:
    proxy-html:
    proxy-certs:
  
networks:
    network:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
