version: '3' 

services:
    document-editor:
        image: onlyoffice/documentserver:latest
        container_name: onlyoffice
        stdin_open: true
        tty: true
        depends_on:
            - proxy
            - letsencrypt
        volumes:
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped 
        
    nextcloud:
        environment: 
            - DOCUMENT_EDITOR=onlyoffice
