version: '3' 

services:
    document_editor:
        image: collabora/code
        container_name: collabora
        depends_on:
            - proxy
            - letsencrypt
        volumes:
            - /etc/localtime:/etc/localtime:ro
        cap_add:
            - MKNOD
        environment:
            - domain=${NEXTCLOUD_SUBDOMAIN}\\.${ESCAPED_DOMAIN}
            - username=${COLLABORA_USERNAME}
            - password=${COLLABORA_PASSWORD}
            - VIRTUAL_PROTO=https
            - VIRTUAL_PORT=443
            - VIRTUAL_HOST=${DOCUMENT_EDITOR_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_HOST=${DOCUMENT_EDITOR_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        restart: unless-stopped 
        
    nextcloud:
        environment: 
            - DOCUMENT_EDITOR=collabora
