version: '3' 

services:
    nextcloud:
        depends_on:
            - antivirus
        
    antivirus:
        image: mkodockx/docker-clamav:latest
        container_name: antivirus
        restart: unless-stopped
