version: '3' 

services:
    collabora:
        image: collabora/code
        container_name: nextcloud-collabora
        networks:
            - nextcloud_network
        depends_on:
            - proxy
            - letsencrypt
        cap_add:
            - MKNOD
        environment:
            - domain=${NEXTCLOUD_SUBDOMAIN}\\.${ESCAPED_DOMAIN}
            - username=${COLLABORA_USERNAME:-admin}
            - password=${COLLABORA_PASSWORD}
            - VIRTUAL_PROTO=https
            - VIRTUAL_PORT=443
            - VIRTUAL_HOST=${COLLABORA_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_HOST=${COLLABORA_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        restart: unless-stopped 
