version: '3' 

services:
    onlyoffice:
        image: onlyoffice/documentserver:latest
        container_name: onlyoffice
        stdin_open: true
        tty: true
        networks:
            - nextcloud_network
        depends_on:
            - proxy
            - letsencrypt
        environment:
            - VIRTUAL_HOST=onlyoffice.${DOMAIN}
            - LETSENCRYPT_HOST=onlyoffice.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        restart: unless-stopped 
