version: '3' 

services:
    nextcloud:
        environment:
            - SMTP_HOST=mail
            - MAIL_FROM_ADDRESS=admin
            - MAIL_DOMAIN=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
    
    mail:
        image: elsdoerfer/exim-sender
        container_name: mail
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ALLOWED_HOSTS=172.16.0.1/16
            - PRIMARY_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
        restart: unless-stopped
