version: '3' 

services:
    onlyoffice:
        image: onlyoffice/documentserver:latest
        container_name: onlyoffice
        stdin_open: true
        tty: true
        networks:
            - network
        depends_on:
            - proxy
            - letsencrypt
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - VIRTUAL_HOST=${ONLYOFFICE_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_HOST=${ONLYOFFICE_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        restart: unless-stopped 
        
    nextcloud:
        environment: 
            - DOCS_EDITOR=onlyoffice
            - ONLYOFFICE_VIRTUAL_HOST=${ONLYOFFICE_SUBDOMAIN}.${DOMAIN}
