version: '3' 

services:

    proxy:
        image: jwilder/nginx-proxy:alpine
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
        container_name: nextcloud-proxy
        networks:
            - nextcloud_network
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./proxy/conf.d:/etc/nginx/conf.d:rw
            - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
            - ./proxy/html:/usr/share/nginx/html:rw
            - ./proxy/certs:/etc/nginx/certs:ro
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: unless-stopped
  
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nextcloud-letsencrypt
        depends_on:
            - proxy
        networks:
            - nextcloud_network
        volumes:
            - ./proxy/certs:/etc/nginx/certs:rw
            - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
            - ./proxy/html:/usr/share/nginx/html:rw
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
    
    database:
        image: mariadb
        container_name: nextcloud-database
        networks:
            - nextcloud_network
        volumes:
            - db:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
            - MYSQL_USER=${MYSQL_USER:-nextcloud}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: unless-stopped
  
    nextcloud:
        image: nextcloud:latest
        container_name: nextcloud-app
        networks:
            - nextcloud_network
        depends_on:
            - letsencrypt
            - proxy
            - database
        volumes:
            - nextcloud:/var/www/html
            - ./app/config:/var/www/html/config
            - ./app/custom_apps:/var/www/html/custom_apps
            - ./app/data:/var/www/html/data
            - ./app/themes:/var/www/html/themes
            - /etc/localtime:/etc/localtime:ro
        environment:
            - VIRTUAL_HOST=nextcloud.${DOMAIN:?You must set the DOMAIN}
            - LETSENCRYPT_HOST=nextcloud.${DOMAIN:?You must set the DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL:?You must set the EMAIL}
        restart: unless-stopped
    
    collabora:
        image: collabora/code
        container_name: nextcloud-collabora
        networks:
            - nextcloud_network
        depends_on:
            - proxy
            - letsencrypt
        cap_add:
            - MKNOD
        ports:
            - 9980:9980
        environment:
            - domain=nextcloud\\.${ESCAPED_DOMAIN:?You must set the ESCAPED_DOMAIN}
            - username=${COLLABORA_USERNAME:-admin}
            - password=${COLLABORA_PASSWORD}
            - VIRTUAL_PROTO=https
            - VIRTUAL_PORT=443
            - VIRTUAL_HOST=collabora.${DOMAIN:?You must set the DOMAIN}
            - LETSENCRYPT_HOST=collabora.${DOMAIN:?You must set the DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL:?You must set the EMAIL}
        restart: unless-stopped 
volumes:
    nextcloud:
    db: 
  
networks:
    nextcloud_network: