version: '3' 

services:
    proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: proxy
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
        ports:
            - 80:80
            - 443:443
        volumes:
            - proxy_conf:/etc/nginx/conf.d:rw
            - proxy_vhost:/etc/nginx/vhost.d:rw
            - proxy_html:/usr/share/nginx/html:rw
            - ./data/proxy/certs:/etc/nginx/certs:ro
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./proxy/upload_limits.conf:/etc/nginx/conf.d/upload_limits.conf:ro
        restart: unless-stopped
  
    database:
        image: mariadb
        container_name: database
        volumes:
            - ./data/database:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: unless-stopped
  
    nextcloud:
        image: nextcloud:18
        container_name: nextcloud
        depends_on:
            - proxy
            - letsencrypt
            - database
            - redis
        volumes:
            - ./data/nextcloud/www:/var/www/html
            - /etc/localtime:/etc/localtime:ro
            - ./nextcloud/setup.sh:/setup.sh
        environment:
            - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
            - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=database
            - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
            - REDIS_HOST=redis
            - VIRTUAL_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
            - DEFAULT_APPS=${DEFAULT_APPS}
            - DEFAULT_ADMIN_APPS=${DEFAULT_ADMIN_APPS}
            - DOCUMENT_EDITOR_HOST=${DOCUMENT_EDITOR_SUBDOMAIN}.${DOMAIN}
            - ONLYOFFICE_URL=${DOCUMENT_EDITOR_SUBDOMAIN}.${DOMAIN}
            - NEXTCLOUD_UPDATE=1
            - SKIP_INITIAL_SETUP=0
            - LDAP_ENABLED=yes
            - NEXTCLOUD_TABLE_PREFIX=
        command: /setup.sh apache2-foreground
        restart: unless-stopped
        
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        depends_on:
            - proxy
        volumes:
            - ./data/proxy/certs:/etc/nginx/certs:rw
            - proxy_vhost:/etc/nginx/vhost.d:rw
            - proxy_html:/usr/share/nginx/html:rw
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        
    cron:
        image: rcdailey/nextcloud-cronjob:latest
        container_name: cron
        depends_on:
            - nextcloud
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - NEXTCLOUD_CONTAINER_NAME=nextcloud
        network_mode: none
        restart: unless-stopped
        
volumes:
    proxy_conf:
    proxy_vhost:
    proxy_html:
  
networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}
