version: '3' 

services:
    document_editor:
        image: collabora/code
        container_name: collabora
        networks:
            - network
        depends_on:
            - proxy
            - letsencrypt
        volumes:
            - /etc/localtime:/etc/localtime:ro
        cap_add:
            - MKNOD
        environment:
            - domain=${NEXTCLOUD_SUBDOMAIN}\\.${ESCAPED_DOMAIN}
            - username=${COLLABORA_USERNAME}
            - password=${COLLABORA_PASSWORD}
        restart: unless-stopped 
        
    nextcloud:
        environment: 
            - DOCUMENT_EDITOR=collabora
