version: "3"

services:
  traefik:
    image: traefik:alpine
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/traefik.toml:/traefik.toml
      - traefik_certificates:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
    command: --docker.domain=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN} --acme.email=${EMAIL}
    restart: unless-stopped
        
  nextcloud:
    image: nextcloud:18
    container_name: nextcloud
    depends_on:
      - traefik
      - database
      - redis
      - antivirus
      - onlyoffice
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.frontend.redirect.regex=https://:${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}/.well-known/(card|cal)dav"
      - "traefik.frontend.redirect.replacement=https://:${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}/remote.php/dav/"
      - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:max-age=15552000; includeSubDomains; preload"
    volumes:
      - nextcloud_www:/var/www/html
      - ./nextcloud/setup.sh:/setup.sh
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=database
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
      - REDIS_HOST=redis
      - DEFAULT_APPS=${DEFAULT_APPS}
      - DEFAULT_ADMIN_APPS=${DEFAULT_ADMIN_APPS}
      - ONLYOFFICE_URL=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}/onlyoffice
      - NEXTCLOUD_UPDATE=1
      - SKIP_INITIAL_SETUP=0
      - NEXTCLOUD_TABLE_PREFIX=
      - SMTP_HOST=mail
      - MAIL_FROM_ADDRESS=admin@${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
      - MAIL_DOMAIN=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
    command: /setup.sh apache2-foreground
    restart: unless-stopped

  database:
    image: mariadb
    container_name: database
    volumes:
      - database_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    stdin_open: true
    tty: true
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=onlyoffice"
      - "traefik.frontend.rule=Host:${NEXTCLOUD_SUBDOMAIN}.${DOMAIN};PathPrefixStrip:/onlyoffice"
      - "traefik.frontend.headers.customRequestHeaders=X-Forwarded-Host:${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}/onlyoffice"
    volumes:
      - onlyoffice_cache:/var/lib/onlyoffice/documentserver/App_Data/cache
      - onlyoffice_database:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  mail:
    image: elsdoerfer/exim-sender
    container_name: mail
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ALLOWED_HOSTS=${SUBNET}
      - PRIMARY_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  antivirus:
    image: mkodockx/docker-clamav:latest
    container_name: antivirus
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  cron:
    image: rcdailey/nextcloud-cronjob:latest
    container_name: cron
    depends_on:
      - nextcloud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud
    network_mode: none
    restart: unless-stopped

volumes:
  traefik_certificates:
  proxy_certs:
  database_data:
  nextcloud_www:
  onlyoffice_cache:
  onlyoffice_database:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
